# Generated by Django 5.2.3 on 2025-07-11 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cpf', models.TextField(blank=True, null=True)),
                ('file_name', models.TextField(blank=True, null=True)),
                ('file_id', models.IntegerField(blank=True, null=True)),
                ('file_hash', models.TextField(blank=True, null=True)),
                ('signature_id', models.IntegerField(blank=True, null=True)),
                ('deal_id', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(blank=True, null=True)),
                ('qtd_signs', models.IntegerField(blank=True, null=True)),
                ('gcp_path', models.TextField(blank=True, null=True)),
                ('full_signed', models.BooleanField(default=False)),
                ('aws_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('momment', models.DateTimeField(blank=True, null=True)),
                ('id_signatario', models.IntegerField(blank=True, null=True)),
                ('id_sign', models.IntegerField(blank=True, null=True)),
                ('sign_hash', models.TextField(blank=True, null=True)),
                ('cpf', models.TextField(blank=True, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doc_sign.documento')),
            ],
        ),
    ]
