# Generated by Django 5.2.3 on 2025-07-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_sign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='criado_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
