# Generated by Django 5.2.3 on 2025-07-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_sign', '0002_alter_documento_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='tipo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
