# Generated by Django 5.2.3 on 2025-07-14 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_sign', '0003_assinatura_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='is_to_sign',
            field=models.BooleanField(default=False),
        ),
    ]
