# Generated by Django 5.2.3 on 2025-07-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_sign', '0004_documento_is_to_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinatura',
            old_name='momment',
            new_name='send_at',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='ip_assinatura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
